package com.vtluan.place_order_football.model;

import java.time.LocalDate;
import java.util.List;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PrePersist;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
public class TimeFrame {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    long id;
    String time;

    LocalDate today;
    boolean isBooked;
    @OneToMany(mappedBy = "timeFrame")
    List<FootballFieldAndTimeFrame> footballFieldAndTimeFrames;

    @PrePersist
    void autoGenerated() {
        this.today = LocalDate.now();
        this.isBooked = false;
    }
}
