package com.vtluan.place_order_football.model;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
@JsonInclude(value = Include.NON_NULL)
public class TimeFrame {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    long id;
    // Description time
    String timeDes;

    @JsonFormat(pattern = "HH:mm")
    LocalTime begin;
    @JsonFormat(pattern = "HH:mm")
    LocalTime end;

    @OneToMany(mappedBy = "timeFrame")
    @JsonIgnore
    List<FootballFieldChildAndTimeFrame> footballFieldAndTimeFrames;

    @PrePersist
    @PreUpdate
    void autoGenerated() {
        this.end = begin.plusHours(1);
        this.timeDes = begin.toString() + " - " + end.toString();
    }
}
